### ISSUE TITLE
Error when run sh start_threatupload.sh

### ISSUE THREAD

**Issue by joya28** [rstcloud/threatdb#1]
I get error when update new version 1.1, when i run sh i get this error
```
'start_threatupload.sh: line 45: syntax error near unexpected token `do
'start_threatupload.sh: line 45: `for i in ${feeds_list[@]}; do
```

**Comment by nikolaiav** [comment]
Hello. 
I tested .sh on CentOS 7.5 fnd Debian 8, it works greate.
Does it work, if  line 45 change to 
`for i in ${feeds_list[@]} 
do`
?

**Comment by joya28** [comment]
Hi nikolaiav
Thanks for you help, i tried your new start_threatupload.sh but i get new error
```
: command not foundsh: line 2:
start_threatupload.sh: line 48: syntax error near unexpected token `do
start_threatupload.sh: line 48: `do
```

**Comment by nikolaiav** [comment]
What Linux distr do you use?
Maybe your shell not lokated in /bin. Check  it with `env|grep SHELL`

**Comment by joya28** [comment]
I'm using CentOS release 6.8 (Final)
#env|grep SHELL
_SHELL=/bin/bash_

**Comment by nikolaiav** [comment]
Tested script on clean installation CentOS 6.8
All works greate [Proof screen](https://drive.google.com/file/d/0B5vpm8jLmoaNckhTLWRPd2prcW8/view?usp=sharing) 
Maybe you are in chroot mode, or haven't SH shell? 
Try to change first line `#!/bin/sh` to`#!/bin/bash`

**Comment by nikolaiav** [comment]
I found same problem on stackoverflow. Also try this [solution]( http://stackoverflow.com/questions/21370059/why-is-this-simple-for-loop-in-my-linux-bash-not-working)

**Comment by joya28** [comment]
Sorry nikolaiav, i just finished a team building in 3 day. I'm using your new start_threatupload.sh and it work perfect.
Thank so much
