### ISSUE TITLE
Can't search with threatDB

### ISSUE THREAD

**Issue by joya28** [rstcloud/threatdb#2]
When i try search with threatDB:
`host="10.88.91.130" | stats count by dest_ip | `threatDB(dest_ip)` | where NOT threatscore=0`
I get error:
_Error in 'SearchParser': The search specifies a macro 'threatDB' that cannot be found. Reasons include: the macro name is misspelled, you do not have "read" permission for the macro, or the macro has not been shared with this application. Click Settings, Advanced search, Search Macros to view macro information._

**Comment by nikolaiav** [comment]
1. Check `Apps -> Manage Apps -> Threat Database -> Permissions`
"Sharing for config file-only objects" must be set on All apps
2. Events field name on threatDB param must be "clientip". Try to modify your search query like that  `host="10.88.91.130" | stats count by dest_ip |rename dest_ip as clientip | ...`
The next version of threatDB also will have params for lookup on domain name reputation base.

**Comment by joya28** [comment]
I followed your guide:
1. Checked "All apps" in "Sharing for config file-only objects" 
2. rename dest_ip as clientip
But when i try command 
`| stats count by dest_ip | rename dest_ip as clientip | `threatDB(clientip)`| where NOT threatscore=0`
i still get this error:

> Error in 'SearchParser': The search specifies a macro 'threatDB' that cannot be found. Reasons include: the macro name is misspelled, you do not have "read" permission for the macro, or the macro has not been shared with this application. Click Settings, Advanced search, Search Macros to view macro information.

**Comment by nikolaiav** [comment]
Look in `Settings - Advanced search - Search macros, App context: Threat Database`. On Permissions for threatDB() "Object should appear in" must be set on "All apps".
Also look in `Settings - Lookups - Lookup definitions, App context: Threat Database`  On Permissions for lookupthreat "Object should appear in" must be set on "All apps"

Try to execute search `| stats count by dest_ip | rename dest_ip as clientip |lookup local=true lookupthreat clientip | where NOT threatscore=0`

**Comment by joya28** [comment]
When i looking in `Settings - Advanced search - Search macros, App context: Threat Database`, i don't see any macro here.
When i try with `| stats count by dest_ip | rename dest_ip as clientip |lookup local=true lookupthreat clientip | where NOT threatscore=0`, i get error `Script for lookup table 'lookupthreat' returned error code 1. Results may be incorrect.`
![image](https://cloud.githubusercontent.com/assets/20811010/17576355/0ec6e156-5f9c-11e6-89ac-91e1ffa19b8a.png)

**Comment by nikolaiav** [comment]
Hello. We've updated Splunk Add-on. Try to use new version from [Splunkbase ](https://splunkbase.splunk.com/app/3236/)
